# Generated by Django 5.2.5 on 2026-08-10 14:19

import django.db.models.deletion
import math
import re
from django.db import migrations, models


def _normalise_name(value):
    value = str(value or '').strip()
    value = re.sub(r'^(?:[-*#\d\.、）)]+\s*)', '', value).strip()
    return re.sub(r'\s+', '', value).casefold()


def migrate_json_trees(apps, schema_editor):
    """把已有 AbilityMap.abilities_json 一次性转换为正式节点记录。"""
    AbilityMap = apps.get_model('ability', 'AbilityMap')
    CapabilityNode = apps.get_model('ability', 'CapabilityNode')
    College = apps.get_model('organizations', 'College')

    for ability_map in AbilityMap.objects.all().iterator():
        tree = ability_map.abilities_json or []
        point_count = 0
        ability_count = 0
        for ability_order, ability_data in enumerate(tree):
            ability_name = str(ability_data.get('name') or '').strip()
            if not ability_name:
                continue
            college_name = str(ability_data.get('college') or '').strip()
            college = College.objects.filter(name=college_name).first() if college_name else None
            ability, _ = CapabilityNode.objects.get_or_create(
                job_id=ability_map.job_id,
                parent_id=None,
                node_type='ability',
                normalized_name=_normalise_name(ability_name),
                defaults={
                    'name': ability_name,
                    'college_id': college.id if college else None,
                    'origin': 'legacy',
                    'is_enabled': ability_data.get('enabled', True) is not False,
                    'sort_order': ability_order,
                },
            )
            ability_count += 1
            units = ability_data.get('units')
            if units is None:
                points = ability_data.get('children', []) or []
                size = math.ceil(len(points) / 3) if points else 1
                units = [
                    {
                        'name': f'能力单元 {index // size + 1}',
                        'enabled': ability_data.get('enabled', True),
                        'children': points[index:index + size],
                    }
                    for index in range(0, len(points), size)
                ]
            for unit_order, unit_data in enumerate(units or []):
                unit_name = str(unit_data.get('name') or '').strip()
                if not unit_name:
                    continue
                unit, _ = CapabilityNode.objects.get_or_create(
                    job_id=ability_map.job_id,
                    parent_id=ability.id,
                    node_type='unit',
                    normalized_name=_normalise_name(unit_name),
                    defaults={
                        'name': unit_name,
                        'origin': 'legacy',
                        'is_enabled': unit_data.get('enabled', True) is not False,
                        'sort_order': unit_order,
                    },
                )
                for point_order, point_data in enumerate(unit_data.get('children', []) or []):
                    point_name = str(point_data.get('name') or '').strip()
                    if not point_name:
                        continue
                    _, created = CapabilityNode.objects.get_or_create(
                        job_id=ability_map.job_id,
                        parent_id=unit.id,
                        node_type='point',
                        normalized_name=_normalise_name(point_name),
                        defaults={
                            'name': point_name,
                            'origin': 'legacy',
                            'is_enabled': point_data.get('enabled', True) is not False,
                            'sort_order': point_order,
                        },
                    )
                    point_count += int(created)
        ability_map.total_abilities = ability_count
        ability_map.total_skills = point_count
        ability_map.save(update_fields=['total_abilities', 'total_skills'])


def reverse_json_trees(apps, schema_editor):
    CapabilityNode = apps.get_model('ability', 'CapabilityNode')
    CapabilityNode.objects.filter(origin='legacy').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0003_abilitymap_review_status'),
        ('chain', '0002_chain_job_enabled'),
        ('crawl', '0004_alter_joblisting_task'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('failed', '分析失败')], db_index=True, default='pending', max_length=20, verbose_name='分析状态')),
                ('input_listing_count', models.PositiveIntegerField(default=0, verbose_name='输入招聘数据数量')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='使用的大模型')),
                ('raw_ai_output', models.TextField(blank=True, verbose_name='AI 原始输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('crawl_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_batches', to='crawl.crawltask', verbose_name='来源采集任务')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_batches', to='chain.job', verbose_name='所属岗位')),
            ],
            options={
                'verbose_name': 'AI 分析批次',
                'verbose_name_plural': 'AI 分析批次',
                'db_table': 'analysis_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('ability', '岗位能力'), ('unit', '能力单元'), ('point', '知识点/技能点')], max_length=20, verbose_name='节点类型')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('normalized_name', models.CharField(editable=False, max_length=200, verbose_name='标准化名称')),
                ('origin', models.CharField(choices=[('manual', '人工创建'), ('ai', 'AI 分析并引用'), ('legacy', '历史 JSON 迁移')], default='manual', max_length=20, verbose_name='节点来源')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='同级排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capability_nodes', to='organizations.college', verbose_name='所属学院')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_nodes', to='chain.job', verbose_name='所属岗位')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ability.capabilitynode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '能力节点',
                'verbose_name_plural': '能力节点',
                'db_table': 'capability_node',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('ability', '岗位能力'), ('unit', '能力单元'), ('point', '知识点/技能点')], max_length=20, verbose_name='节点类型')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('normalized_name', models.CharField(editable=False, max_length=200, verbose_name='标准化名称')),
                ('decision_status', models.CharField(choices=[('not_required', '已存在，无需处理'), ('pending', '等待处理'), ('adopted', '已引用'), ('rejected', '已拒纳')], db_index=True, default='pending', max_length=20, verbose_name='处理状态')),
                ('decision_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('evidence_json', models.JSONField(blank=True, default=list, verbose_name='分析证据')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='同级排序')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ability.analysisbatch', verbose_name='所属分析批次')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_nodes', to='organizations.college', verbose_name='建议所属学院')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ability.analysisnode', verbose_name='父分析节点')),
                ('matched_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_matches', to='ability.capabilitynode', verbose_name='匹配的正式能力节点')),
            ],
            options={
                'verbose_name': 'AI 分析节点',
                'verbose_name_plural': 'AI 分析节点',
                'db_table': 'analysis_node',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='capabilitynode',
            index=models.Index(fields=['job', 'parent'], name='cap_node_job_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='capabilitynode',
            index=models.Index(fields=['job', 'node_type'], name='cap_node_job_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='capabilitynode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('job', 'node_type', 'normalized_name'), name='uniq_root_capability_name'),
        ),
        migrations.AddConstraint(
            model_name='capabilitynode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('job', 'parent', 'node_type', 'normalized_name'), name='uniq_child_capability_name'),
        ),
        migrations.AddIndex(
            model_name='analysisnode',
            index=models.Index(fields=['batch', 'parent'], name='ana_node_batch_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisnode',
            index=models.Index(fields=['batch', 'decision_status'], name='ana_node_batch_state_idx'),
        ),
        migrations.RunPython(migrate_json_trees, reverse_json_trees),
    ]
