# Generated by Django 5.2.5 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ability", "0006_capabilitynode_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitynode",
            name="course_matches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='匹配课程列表，例如：[{"course_name": "数控加工工艺", "matched_content": "工序划分"}]。',
                verbose_name="匹配课程",
            ),
        ),
    ]
