# Generated by Django 6.0.7 on 2026-07-31 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities_json', models.JSONField(default=list, verbose_name='能力列表JSON')),
                ('total_abilities', models.IntegerField(default=0, verbose_name='能力项数')),
                ('total_skills', models.IntegerField(default=0, verbose_name='技能点数')),
                ('raw_text', models.TextField(blank=True, verbose_name='原始AI输出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ability_map', to='chain.job', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '能力图谱',
                'verbose_name_plural': '能力图谱',
                'db_table': 'ability_map',
            },
        ),
    ]
