# Generated by Django 5.0.14 on 2026-08-24 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_coursetreenode_chapter_content_edited'),
        ('organizations', '0005_delete_college'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classes', models.ManyToManyField(related_name='teaching_arrangements', to='organizations.class', verbose_name='授课班级')),
                ('course_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_arrangements', to='curriculum.coursetree', verbose_name='教学课程')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_arrangements', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '教学安排',
                'verbose_name_plural': '教学安排',
                'db_table': 'teaching_arrangement',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'course_tree', 'semester')},
            },
        ),
    ]
