# Generated by Django 5.0.14 on 2026-08-13 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login', '登录日志'), ('operation', '操作日志')], max_length=20, verbose_name='日志类型')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='操作人名称')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='IP')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'notification_system_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('type', models.CharField(choices=[('system', '系统公告')], default='system', max_length=20, verbose_name='类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('offline', '已下架')], default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.role', verbose_name='受众角色')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='已读时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知已读记录',
                'verbose_name_plural': '通知已读记录',
                'db_table': 'notification_notice_read',
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
