# Generated by Django 6.0.7 on 2026-07-31 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('total_keywords', models.IntegerField(default=0)),
                ('total_results', models.IntegerField(default=0)),
                ('results_json', models.JSONField(default=list, verbose_name='原始结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='chain.job', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '爬取任务',
                'db_table': 'crawl_task',
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='岗位名称')),
                ('company', models.CharField(max_length=200, verbose_name='公司')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='薪资')),
                ('education', models.CharField(blank=True, max_length=50, verbose_name='学历')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('headcount', models.CharField(blank=True, max_length=20, verbose_name='招聘人数')),
                ('post_date', models.CharField(blank=True, max_length=50, verbose_name='发布日期')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='来源')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='crawl.crawltask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '招聘信息',
                'db_table': 'job_listing',
            },
        ),
    ]
