# Generated by Django 5.2.5 on 2026-08-10 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='来源名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='来源编码')),
                ('base_url', models.URLField(max_length=500, verbose_name='来源地址')),
                ('interval_minutes', models.PositiveIntegerField(default=1440, validators=[django.core.validators.MinValueValidator(1)], verbose_name='采集间隔（分钟）')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='附加配置')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'crawl_source',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='crawltask',
            options={'verbose_name': '采集任务', 'verbose_name_plural': '采集任务'},
        ),
        migrations.AddField(
            model_name='crawltask',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='new_results',
            field=models.IntegerField(default=0, verbose_name='新增结果数'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划执行时间'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='trigger_type',
            field=models.CharField(choices=[('manual', '手动触发'), ('scheduled', '定时触发')], default='manual', max_length=20, verbose_name='触发方式'),
        ),
        migrations.AlterField(
            model_name='crawltask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='crawltask',
            name='status',
            field=models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('completed', '执行完成'), ('failed', '执行失败')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='crawltask',
            name='total_keywords',
            field=models.IntegerField(default=0, verbose_name='关键词数量'),
        ),
        migrations.AlterField(
            model_name='crawltask',
            name='total_results',
            field=models.IntegerField(default=0, verbose_name='采集结果数'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crawl.crawlsource', verbose_name='采集来源'),
        ),
    ]
