# Generated by Django 5.2.5 on 2026-08-10 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_chain_job_enabled'),
        ('crawl', '0002_crawlsource_alter_crawltask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'verbose_name': '招聘信息', 'verbose_name_plural': '招聘信息'},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='crawl_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_listings', to='crawl.crawlsource', verbose_name='采集来源配置'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='数据指纹'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='first_seen_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='首次发现时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='chain.job', verbose_name='所属岗位'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最近发现时间'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='raw_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始数据'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='招聘详情地址'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='原始来源名称'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='crawl.crawltask', verbose_name='所属采集任务'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.UniqueConstraint(fields=('job', 'crawl_source', 'fingerprint'), name='unique_listing_per_job_source'),
        ),
    ]
