# Generated by Django 5.2.5 on 2026-08-10 14:19

import django.db.models.deletion
import hashlib
from django.db import migrations, models


def backfill_listing_identity(apps, schema_editor):
    JobListing = apps.get_model('crawl', 'JobListing')
    for listing in JobListing.objects.select_related('task').all().iterator():
        if listing.task_id:
            listing.job_id = listing.task.job_id
            listing.crawl_source_id = listing.task.source_id
        raw = '|'.join([
            str(listing.title or '').strip().casefold(),
            str(listing.company or '').strip().casefold(),
            str(listing.city or '').strip().casefold(),
            str(listing.source_url or '').strip().casefold(),
            str(listing.requirements or '')[:200].strip().casefold(),
        ])
        fingerprint = hashlib.sha256(raw.encode('utf-8')).hexdigest()
        duplicate_exists = JobListing.objects.exclude(id=listing.id).filter(
            job_id=listing.job_id,
            crawl_source_id=listing.crawl_source_id,
            fingerprint=fingerprint,
        ).exists()
        listing.fingerprint = None if duplicate_exists else fingerprint
        listing.save(update_fields=['job', 'crawl_source', 'fingerprint'])


def reverse_listing_identity(apps, schema_editor):
    JobListing = apps.get_model('crawl', 'JobListing')
    JobListing.objects.update(job_id=None, crawl_source_id=None, fingerprint=None)


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_alter_joblisting_options_joblisting_crawl_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='crawl.crawltask', verbose_name='所属采集任务'),
        ),
        migrations.RunPython(backfill_listing_identity, reverse_listing_identity),
    ]
