# Generated by Django 5.2.5 on 2026-08-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_chain_job_enabled'),
        ('crawl', '0005_move_analysis_models_from_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisbatch',
            name='status',
            field=models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('skipped', '数据不足，已跳过'), ('failed', '分析失败')], db_index=True, default='pending', max_length=20, verbose_name='分析状态'),
        ),
        migrations.AddConstraint(
            model_name='analysisbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('crawl_task__isnull', False)), fields=('crawl_task',), name='uniq_analysis_batch_per_crawl_task'),
        ),
        migrations.AddConstraint(
            model_name='crawltask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('job', 'source'), name='uniq_active_crawl_task_per_job_source'),
        ),
    ]
