# Generated by Django 5.0.14 on 2026-08-12 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机构名称')),
                ('org_type', models.CharField(choices=[('school', '学校'), ('college', '学院'), ('department', '系部'), ('office', '科室'), ('group', '教研组')], max_length=20, verbose_name='机构类型')),
                ('leader', models.CharField(blank=True, max_length=50, verbose_name='负责人')),
                ('description', models.TextField(blank=True, verbose_name='机构说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organization', verbose_name='上级机构')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
                'db_table': 'organization_org',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='班级编号')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='年级')),
                ('teacher', models.CharField(blank=True, max_length=50, verbose_name='班主任')),
                ('status', models.CharField(choices=[('active', '启用'), ('graduated', '毕业')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='organizations.organization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'organization_class',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='年级')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='organizations.class', verbose_name='所属班级')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联账号')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'organization_student',
                'ordering': ['-created_at'],
            },
        ),
    ]
