# Generated by Django 5.0.14 on 2026-08-12 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_org_class_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_colleges', to='organizations.organization', verbose_name='关联机构'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(max_length=50, verbose_name='机构类型'),
        ),
    ]
