# Generated by Django 5.0.14 on 2026-08-24 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0006_coursetreenode_chapter_content_edited'),
        ('organizations', '0005_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('tag', models.CharField(blank=True, max_length=20, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='organizations.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'learning_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanDeleteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度')),
                ('reason', models.CharField(max_length=200, verbose_name='删除原因')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='删除时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_delete_logs', to='organizations.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学习计划删除日志',
                'verbose_name_plural': '学习计划删除日志',
                'db_table': 'learning_plan_delete_log',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('plan_type', models.CharField(choices=[('semester', '学期计划'), ('self', '自主学习'), ('ai', 'AI推荐')], default='self', max_length=20, verbose_name='计划类型')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('status', models.CharField(choices=[('todo', '未开始'), ('doing', '进行中'), ('done', '已完成')], default='todo', max_length=20, verbose_name='状态')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度')),
                ('learned_hours', models.PositiveIntegerField(default=0, verbose_name='已学学时')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='总学时')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('teacher', models.CharField(blank=True, max_length=50, verbose_name='教师')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_plans', to='curriculum.coursetree', verbose_name='课程树')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='organizations.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学习计划',
                'verbose_name_plural': '学习计划',
                'db_table': 'learning_plan',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course_tree', 'plan_type')},
            },
        ),
    ]
