# Generated by Django 5.0.14 on 2026-09-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_coursetreenode_chapter_content_edited'),
        ('learning', '0001_initial'),
        ('organizations', '0005_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to='curriculum.coursetreenode', verbose_name='知识点')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to='organizations.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'db_table': 'learning_progress',
                'unique_together': {('student', 'node')},
            },
        ),
    ]
