# Generated by Django 5.0.14 on 2026-09-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_coursetreenode_chapter_content_edited'),
        ('learning', '0002_learningprogress'),
        ('organizations', '0005_delete_college'),
        ('teaching', '0002_teachingarrangement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('point', '知识点'), ('chapter', '章节'), ('course', '课程')], max_length=20, verbose_name='测评范围')),
                ('title', models.CharField(max_length=200, verbose_name='测评标题')),
                ('question_ids', models.JSONField(default=list, verbose_name='题目id快照')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='得分')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='总分')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='答对数')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='答错数')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='curriculum.coursetreenode', verbose_name='关联节点')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='learning.learningplan', verbose_name='来源学习计划')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_runs', to='organizations.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '测评记录',
                'verbose_name_plural': '测评记录',
                'db_table': 'learning_assessment_run',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.JSONField(default=list, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_answers', to='curriculum.coursetreenode', verbose_name='知识点')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_answers', to='teaching.coursequestion', verbose_name='题目')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.assessmentrun', verbose_name='所属测评')),
            ],
            options={
                'verbose_name': '测评作答',
                'verbose_name_plural': '测评作答',
                'db_table': 'learning_assessment_answer',
            },
        ),
    ]
