# Generated by Django 5.0.14 on 2026-09-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_coursetreenode_chapter_content_edited'),
        ('learning', '0003_assessmentrun_assessmentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='extra_nodes',
            field=models.ManyToManyField(blank=True, related_name='reinforced_plans', to='curriculum.coursetreenode', verbose_name='补强知识点'),
        ),
    ]
