# Generated by Django 5.0.14 on 2026-09-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_coursetreenode_chapter_content_edited'),
        ('learning', '0004_learningplan_extra_nodes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningplan',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PlanCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_courses', to='curriculum.coursetree', verbose_name='课程')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='learning.learningplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': '计划课程',
                'verbose_name_plural': '计划课程',
                'db_table': 'learning_plan_course',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('plan', 'course_tree')},
            },
        ),
        migrations.RemoveField(
            model_name='learningplan',
            name='course_tree',
        ),
        migrations.RemoveField(
            model_name='learningplan',
            name='extra_nodes',
        ),
        migrations.CreateModel(
            name='PlanPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_points', to='curriculum.coursetreenode', verbose_name='知识点')),
                ('plan_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='learning.plancourse', verbose_name='所属计划课程')),
            ],
            options={
                'verbose_name': '计划知识点',
                'verbose_name_plural': '计划知识点',
                'db_table': 'learning_plan_point',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('plan_course', 'node')},
            },
        ),
    ]
