# Generated by Django 6.0.7 on 2026-07-31 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产业链名称')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产业链',
                'verbose_name_plural': '产业链',
                'db_table': 'chain',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标准岗位名')),
                ('aliases', models.JSONField(default=list, verbose_name='别名列表')),
                ('search_keywords', models.JSONField(default=list, verbose_name='搜索关键词')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='已确认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='chain.chain', verbose_name='所属产业链')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'db_table': 'job',
                'unique_together': {('chain', 'name')},
            },
        ),
    ]
